# Generated by Django 5.0 on 2023-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='240', null=True, upload_to='uploads/', width_field='240'),
        ),
    ]
